README.md
There are some missing line breaks in the README. I also updated the quickstart link to go directly to the Quickstart page.
=> docs: fix formatting in readme

docs/install.md
Fixes https://github.com/lightninglabs/pool/issues/140.
The expected configuration file name is `poold.conf` but was referenced to in the docs as `pool.conf`.
=> docs: reference correct poold.conf file

cmd/pool/order.go, order/supplyunit.go, order/supplyunit_test.go
Fixes https://github.com/lightninglabs/pool/issues/145.
=> pool: round default min chan amt to nearest unit

account/manager.go, account/manager_test.go
Prevents https://github.com/lightninglabs/pool/issues/146 from happening.
=> rpc: check dust outputs on account withdrawals and closures

server.go
Because of a misplaced defer of a context cancel, the REST proxy didn't
work at all before the fix in this commit.
=> server: fix REST connection

auctioneer/batch.go
This PR fixes https://github.com/lightninglabs/pool/issues/176 where several users reported the trader daemon crashing on startup.
Removed the unused `RelevantBatchSnaphost` RPC as well. @wpaulino wasn't this used for something else too? Did we remove that already? I thought this was vital for something else as well.
=> Fix startup error because of wrong RPC

auctioneer/batch.go, auctioneer/client.go, clientdb/account_test.go, clientdb/db.go, cmd/pool/debug.go, cmd/pool/main.go, fundingmgr_test.go, rpcserver.go, server.go
Adds a debug CLI that helps inspecting a local trader database. Also wraps some errors to give more information about the cause.
EDIT: The advantage of these commands is that they work without starting the trader daemon (so no interaction with the server) and also work on databases of other users, as no interaction with lnd is required either.
Perhaps it's really just something we'll use and it doesn't need to be in the main code base. But I've hidden the command group so most people won't notice this.
=> Add debug CLI and wrap errors

cmd/pool/account.go
Typo on help info of account deposit
=> cmd/pool: fix typo on account deposit

auctioneer/batch.go, auctioneer/client.go, clientdb/batch.go, clientdb/batch_snapshot.go, clientdb/batch_test.go, cmd/pool/debug.go, funding/manager.go, rpcserver.go, server.go
Depends on #187, only the last 5 commits are new.
If a trader shuts down after being involved in a batch that resulted in a pending channel but is never finalized because other traders caused the batch to fail, they never get the chance to clean up those pending channels because the information necessary for that is only kept in memory.
We now also try to clean up pending channels and funding shims on startup if we detect an old, pending batch.
The big refactor in #187 was mainly necessary to do this in a clean way (concerning what component is responsible for what tasks).
For users with existing pending channels prior to this fix (they will never go away), we could add a manual `cleanup` command that:
* Gets all pending channels from `lnd` that have a thaw height
* Ask the auctioneer for …
=> Clean up pending batch artifacts on startup

account/manager.go, auctioneer/client.go
To make the account manager less dependent on the wallet state of lnd,
we use the latest TX state that we now store for the account instead of
the lnd ListTransactions RPC where possible.
This fixes account recovery for lnd nodes that were restored from the
seed and don't remember/detect all Pool transactions automatically.
This should fix the error `2020-12-24 14:46:33.574 [ERR] RPCS: error storing recovered account: account funding TX with output 002033ab6debxxxx not found` that was reported to me on Slack.
=> account: use latest TX from DB instead of querying lnd

rpcserver.go
This change was mostly motivated by the following scenario:
1. Trader accepts and signs a batch proposal, and stores it to disk.
2. Auctioneer send a new batch proposal due to another trader within the batch bailing out.
3. The trader who signed above rejects the new batch proposal.
4. The same trader attempts an account modification (deposit, withdrawal, renewal, etc.).
5. The spend handling logic as part of the account modification commits the staged batch proposal which was replaced, leaving the account state invalid.
This is addressed by removing the staged batch proposal upon any replacements, regardless of whether they are accepted or not. This change also falls in line with the existing work done to clear any artifacts as the result of a previously accepted batch proposal.
=> rpc: delete previous pending batch after receiving replacement

go.mod
Now that we've merged the PR that made auctioneerrpc a submodule and
pushed a tag, we want to reference it with that tag to make the go.mod
file easier to read/understand.
=> mod: use tagged version for auctioneerrpc submodule

auctioneer/client.go, config.go, server.go
This PR adds a SOCKS proxy option to dial to the auction server via TOR.
I oriented myself on the loop implementation.
Runs well on my nix-bitcoin [branch](https://github.com/sputn1ck/nix-bitcoin/tree/lightning-pool-proxy)
fixes #215
=> Add SOCKS proxy option

config.go, server.go, version.go
Fixes two issues I noticed when testing the latest version of Pool in combination with LiT.
=> Provide default value for lnd macaroon path, fix shutdown panic in LiT

sidecar/codec.go, sidecar/codec_test.go, sidecar/interface.go, sidecar/tlv.go, sidecar/tlv_test.go
This is a first preview of the sidecar ticket type and its TLV and string encoders.
> Ticket is a struct holding all the information for establishing/buying a
> sidecar channel. It is meant to be used in a PSBT like manner where each
> participant incrementally adds their information according to their role and
> the current step.
The ticket will replace all new parameters/flags described in https://github.com/guggero/pool/blob/sidecar/docs/sidecar_channels.md.
Instead the ticket will be passed between the participants and enriched with more information in each step.
=> sidecar: add ticket with TLV encoders

rpcserver.go
This problems affected two users who reported on Slack that they were unable to recover their account state.
I've sponsored them an LSAT so they can proceed. This fix should prevent any user with data loss from running into the same problem in the future.
The account recovery process uses a bi-directional streaming RPC on
the server side. Unfortunately, because of the way streaming RPCs
work, the LSAT interceptor isn't able to _purchase_ a token during
a streaming RPC call (the 402/payment required error is only returned
after the interceptor was handed the call, so it cannot act on it
anymore). But since a user that has lost their data most likely als
lost their LSAT, the recovery will fail if this is the first call to
the server ever. That's why we call an RPC that's definitely not on …
=> rpcserver: fix LSAT issue on account recovery

poolrpc/trader.proto
The command example for the `sidecar expectchannel` was incorrect which
lead to the API docs generator erroring out.
=> poolrpc: fix command example that broke API docs

config.go
There is an open issue for Python gRPC clients that is
currently being debugged https://github.com/grpc/grpc/issues/23172
It can be mitigated server-side by specifying h2 in the metadata header.
Tested on macOS and Linux. 
Unsure if this would have any negative side effects on other gRPC client langs.
=> rpcserver: fix Python gRPC client ALPN property error

go.mod, go.sum
Fixes #221
With this commit we update to v0.1.6-beta of the aperture dependency
which fixes the issue of pending LSAT tokens not being removed even if
the payment failed for good.
=> mod: bump aperture to v0.1.6-beta

poolrpc/rest-annotations.yaml
When trying to enable a single unified REST proxy in LiT, we noticed
that one URI collides between Loop and Pool (/v1/lsat/tokens).
We change the URI in Pool to fix the collision.
This is a potentially breaking change! Though we do not use REST in LiT
and are not aware of other projects using Pool's REST API yet so it
should impact a small number of users (or nobody really in the best
case).
Related: https://github.com/lightninglabs/lightning-terminal/pull/216
=> poolrpc: namespace URI of LSAT REST call

auto_sidecar.go, rpcserver.go, sidecar_acceptor.go, sidecar_acceptor_test.go
Without this extra case on restart, the recipient would have an
unhandled state transition that would cause them to not expect the
channel as it should once the batch is finalized.
=> sidecar: on restart ensure recipient re-expects channel

auto_sidecar.go, backoff.go
In this commit, we fix an existing issue that would cause sidecar
negotiation to halt if either the server restarted, or if the main
connection was torn down. To address this, we add a simple abstraction
that implements stateful exponential back-off that'll wait for a period
of time before trying to read from the mailbox again.
=> sidecar: add simple exponential back off for mailbox reads

cmd/pool/sidecar.go
I noticed a bug when using the "pool sidecar offer" command. In either mode, the OfferSidecar command in rpcserver requires the trader key (https://github.com/lightninglabs/pool/blob/a43019f246543b0efac18e2bd6bb72eb61a591fc/rpcserver.go#L2267). But when the "auto" field is not set, the TraderKey field is never set in cmd/pool/sidecar.go.
This is a small proposed change that retrieves the trader key passed in the cli, when not in auto mode.
=> cmd/pool: make sure to retrieve trader key when using sidecarOffer command

config.go, server.go
Attempts to fix the `no_route` error people are running into because the 10 satoshi default routing fee limit for the 1k sat LSAT payment is too restrictive in some situations.
We bump the default to 50 sats and also make the value configurable.
=> Bump default LSAT max routing fee and make it configurable

auctioneer/client.go, rpcserver.go
As is, we only attempt to reconnect if we receive a nice io.EOF error
from the gRPC client, which is usually triggered when the server
shutsdown. However in the wild, possibly due to a load balancer and/or
reverse proxy bug, we encounter another error which as is, doesn't
trigger the usual reconnection logic.
In this commit, we now log any unknown error, but then also attempt to
reconnect again by sending the normal "server shutdown" message.
As is, if this doesn't work after the max number of retries, we won't
retry any longer, but perhaps we should still attempt to retry in the
background.
// EDIT(guggero):
It turns out that on startup the auctioneer can get overwhelmed if
hundreds of traders try to authenticate all at once. So some of them run
into a timeout (which sounds like it's the …
=> auctioneer+rpc: force a reconnection attempt on unknown error

.github/pull_request_template.md, account/manager.go, account/mock_test.go, go.mod, go.sum, internal/test/walletkit_mock.go, server.go
This commit bumps the compile time version of pool to a version of lnd where we have addressed our etcd modules workaround so that code that has already removed the workaround can import pool.
=> gomod: bump to lndclient 13-7

rpcserver.go
Add check for requests with relative AND absolute height provided
instead of using the absolute one by default.
The same check for sats/kw and confirmation target has been moved to the
`switch` statement instead of having it in an extra `if`.
=> account: handle invalid InitAccount parameters

rpcserver.go
The `feeRate` variable was shadowing inside the `req.GetConfTarget() > 0`
switch case. The server was returning an error when the `feeRate` was
estimated using the confirmation target.
```
[ERR] RPCS: [/poolrpc.Trader/InitAccount]: fee rate of 0 sat/kw is too low, minimum is 253 sat/kw
```
=> rpcserver: fix feeRate when using conf target

auto_sidecar.go, cmd/pool/sidecar.go, rpcserver.go, sidecar_acceptor.go, sidecar_acceptor_test.go
Fixes https://github.com/lightninglabs/pool/issues/295.
Fixes https://github.com/lightninglabs/pool/issues/294.
This PR fixes the issue that when one side of a sidecar channel offering cancels the ticket, the other side isn't informed about it. This leads to follow-up errors on restarts and subsequent ticket submissions.
We solve this by sending a message to the other side if we are the cancelling party.
Because we send the message over the mailbox, we cannot remove it in that case.
=> sidecar: inform remote side about cancellation

go.mod, go.sum
Bumps the compile time version of `lnd` to `v0.14.0-beta.rc1` as a preparation to be included in LiT.
used.
=> mod: bump lnd to v0.14.0-beta.rc1

macaroons.go, server.go
In some cases we don't want the default macaroon file to be created on
disk, so we allow passing in a boolean that toggles the macaroon
creation.
This is for the LiT stateless integrated mode.
used.
=> pool: conditionally create default macaroon file

docs/account_recovery.md, docs/accounts.md, docs/batch_execution.md, docs/channel_leases.md, docs/faq.md, docs/orders.md, docs/quickstart.md
I will add more documentation about supporting account auto renewal and client side account recovery after the changes for the client side recovery have been merged and we have a new tagged version.
=> docs: update documentation

auctioneer/account_subscription.go, auctioneer/account_subscription_test.go, auctioneer/client.go, config.go, order/batch.go, order/batch_verifier.go, order/batch_verifier_test.go, order/manager.go, order/manager_test.go, rpcserver.go, server.go
Makes the batch version configurable to enable integration testing of different client batch versions in the same batch.
used.
=> Conditional batch version for itests

cmd/pool/order.go, go.mod, go.sum, order/rpc_parse.go, rpcserver.go, server.go
In this PR, we remove the defaults and the CLI and RPC level. We replace them with a new set of functional options that'll let us decide dynamically which features to use based on the lnd version. This lets us support older versions, while being able to activated newer features as we detect them based on what lnd offers. 
used.
=> multi: remove static default channel types instead select them based on lnd's verison

order/batch_storer.go, order/rpc_parse.go, version.go
Prepare for new client release by bumping the version (and fixing a linter issue left over from #330).
used.
=> Pool 0.5.4

rpcserver.go, server.go
A new variable for the connected lnd node's version was added but was
not given a value when run in subserver mode within LiT.
This commit uses the lnd service's cached version directly and removes
the uninitialized variable.
=> rpcserver: fix nil version in subserver mode

go.mod, go.sum, macaroons.go, server.go
Since the code for creating and using a macaroon service is the same for
multiple projects (pool, loop, litd etc), the code has been unified in
lndclient. So this commit removes the macaroon service code and instead
uses the lndclient code.
Depends on https://github.com/lightninglabs/lndclient/pull/86
=> multi: use lndclient MacaroonService

auto_sidecar.go
Whenever we are are unable to receive a sidecar packet in an auto
sidecar negotiator try to reinitialize its mailbox. This will allow us to
continue reading/writing in the mailbox in cases where the error was
caused by the server going down (and already came back).
=> sidecar: Init mailbox after server restarts

sidecar_acceptor.go
Quick (dirty) fix to ensure that we do not end up in an endless loop of batch rejections. One side effect is that we pollute the logs a bit more (issue #327).
#341 will fix this properly, by ensuring that shim creation after matching is atomic. Meanwhile this unblocks some of our traders.
=> sidecar: clean old shims for orders in current batch

cmd/pool/account.go
Our message was really confusing. If `sat_per_vbyte` was provided, Init account was printing a `conf_target` that was not used at all.
=> cmd: improve InitAccount cli message

sidecar_acceptor.go, version.go
The first commit cleans up the shims whenever we reject a batch.  
The second commit populates the `OrderMatchReject` msg properly.
=> Fix sidecar message handlers

rpcserver.go
The rpcserver cannot have more than one account recovery process running
at once. The server uses a internal attribute (`recoveryPending`) that
is set to true when a new recovery process starts. However, that
attribute was only set to false if the process ended successfully,
leaving the server unable to try more recoveries after a failure.
=> rpcserver: fix `recoveryPending` attribute

Dockerfile
Some users were not able to build [multi arch images with docker](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/). It looks like we need to propagate the `${BUILDPLATFORM}` to all the docker stages.
I also had to bump the go version to make this work `docker buildx build --platform linux/arm64/v8 -f Dockerfile .`, not sure if something changed in the last three versions of go for arm :eyes:
=> docker: bump go version + set arch platform

clientdb/order.go, cmd/pool/debug.go, order/interfaces.go, order/mock_interfaces.go, order/mock_test.go, server.go
Enable deleting orders in the local db using the debug cli. This can be used to clean the local db in case it gets out of sync with the server.
**DANGER**: if the user deletes an order from the local db and that order exists in the server, the user will get disconnected when that order matches (and won't be able to trade). The only solution then is to nuke the local db, restore the account and recreate the orders.
unblocks #357
=> cmd/debug: add DeleteOrder command

rpcserver.go
To fix an accidental market segregation for lnd 0.14.x users that didn't
set an explicit channel type in their bid orders, we roll back the
changes from #330.
We can re-enable this default value selection once a large number of ask
orders support the new channel type.
Fixes https://github.com/lightninglabs/pool/issues/349.
=> rpcserver: roll back #330

auctioneer/errors.go, server.go
The client and server db can get out of sync if some orders are not recorded properly in the server. This becomes problematic because the deamon won't start until all the bad invoices have been cleaned out. Right now the clients need to fix these edge cases manually.
The idea is to simply mark those invoices as failed and let the client continue with the start up.
=> order: Mark missing orders as failed in the client db

poolscript/script.go, poolscript/script_test.go
Something I noticed when taking a closer look at how the btcec V2 library works.
Not sure if this is really necessary or not, any thoughts, @Roasbeef?
The unit tests all passed fine without this, but maybe this could be an edge case?
=> poolscript: make sure negation works with btcec v2

funding/batch.go
If we can't clean up pending channels from a previous batch attempt,
that shouldn't block startup. So instead of shutting down, we just log
the warning and continue.
Not sure how the DB got into that state, but this error is what's preventing LiT from starting in this case: https://github.com/lightninglabs/lightning-terminal/issues/372
used.
=> funding: don't abort if cleanup fails

cmd/poold/main.go, config.go, run.go
Replaces #228.
Makes the IP address of the profile listener configurable and uses `localhost` if only a port is specified.
used.
=> multi: make profile IP configurable

poolscript/script.go, poolscript/script_test.go
This PR extends [`poolscript.IsTaprootExpirySpend`](https://github.com/lightninglabs/pool/blob/409d7abf1ee25b4878d50e52c78ecfa9fab58151/poolscript/script.go#L455) such that Taproot witness annex elements are correctly handled (ignored).
=> taproot: ensure check for expiry script spend correctly handles annex

rpcserver.go
Adds a missing case during the Account Marshall serialization.
=> rpcserver: handle 'StateExpiredPendingUpdate' case for account state

cmd/pool/order.go
=> cmd: make orders public by default

cmd/pool/order.go
Use the right flag in the subcommand help message.
Fix #401
=> cmd: use `--amt` in submit order description

rpcserver.go
=> rpcserver: populate `auction_type` in the ListOrders endpoint

account/manager.go
PR https://github.com/lightninglabs/pool/pull/396 was merged prematurely. This PR addresses any remaining review comments.
=> account: transaction labels code cleanup

cmd/pool/order.go
Skip the extra check in the cli validation flow for the markets where this option is a valid.
This bug only applied to the validation logic in the cli package, poold and the backend services validate the orders correctly.
=> cmd: allow `min_chan_amt > amt` for outbound liquidity orders

Makefile, scripts/release.sh
When building a release we want to use the right tag, even if it was not annotated.
Fix #417
=> scripts: use `git describe --tags`

Dockerfile
This commit separates the task of dependencies installation into its own separate run layer. Previously, dependencies installation shared the same layer as local repo build.
This change means that the dependencies run layer can be reused (cached) whilst the local repo is modified. Which is helpful for regtests.
I've tested this change by building the docker image.
used.
=> docker: perform dependencies installation in separate run layer

config.go, rpcserver.go, run.go
Add `RequestShutdown` option to Pool's config that callers running pool as a subserver can set to whatever they want. By default the function will be a no-op. In the case where Pool is running as a standalone binary, the call-backs will call the corresponding signal interceptor function.
=> multi: configurable RequestShutdown call-back in config

.github/workflows/main.yml, .golangci.yml, Dockerfile, auctioneerrpc/auctioneer.pb.go, auctioneerrpc/hashmail.pb.go, auctioneerrpc/hashmail_grpc.pb.go, clientdb/batch_snapshot.go, gen/Dockerfile, poolrpc/Dockerfile, poolrpc/trader.pb.go, poolrpc/trader_grpc.pb.go, poolscript/script.go, sidecar_acceptor.go, tools/Dockerfile
- Since Go v1.19.0 `go fmt` also formats commented code so files need to be reformated.
- Includes the fix for the lint complains about vsc
P.S: I can extract some of the steps in the actions in a comment one for  `Seting up Golang environment` if needed in this PR too
=> build: update go to v1.19.4-beta

rpcserver.go, tools/Dockerfile
We were using `Error(<string>, <err>)` instead of `Errorf(<string>, <err>)`. The error was appended at the end of the message instead of replacing the `%v` tag in the message.
Fixes #425
=> rpcserver: format rpcLog error

order/rpc_parse.go, order/rpc_parse_test.go, rpcserver.go, tools/Dockerfile
=> rpc: populate allowed/not allowed node ids when listing orders

make/release_flags.mk
lnd PR https://github.com/lightningnetwork/lnd/pull/7252/ removed support for 10 OS / architectures
As Pool requires lnd to run, this PR replicates the build list of lnd for Pool.
It is assumed that if a developer builds for an unsupported OS/architecture for their lnd binaries, the same will be done for Pool
=> build: remove Pool release targets no longer built for lnd

server.go, version.go
Now that lnd `v0.16.0-beta.rc` is out we can target the right lnd version for `muSig2V100RC2Version`.
**Note**: we may want to set the minimum supported version for LND to `v0.16.0-beta`
=> version: bump to v0.6.2-beta

server.go, version.go
With this commit we instruct the gRPC client to ping the server every 10 seconds to make sure the TCP connection is still alive.
Tested with Wireshark.
used.
=> server: specify gRPC keepalive params

go.mod, go.sum
This is the same as v0.18.0-beta.
used.
=> go.mod: update LND to v0.18.0-beta.1

docs/batch_execution.md, docs/sidecar_channels.md
=> chore: fix some typos

poolrpc/perms.go, server.go
Context: https://github.com/lightninglabs/lightning-node-connect/pull/114#discussion_r2078197455
---
This change narrows the import scope for lightning-node-connect (LNC). Instead of importing the entire pool package, LNC now only needs to import poolrpc.
It also brings pool in line with the structure used in our other projects.
=> perms: move perms.go into poolrpc

funding/manager.go, funding/manager_test.go
In this commit, we fix a few issues with the streaming handling:
1. If it got an error on Recv() it would just spin for ever, generating an endless stream of spammy logs.
2. It never listened on the Done() context channel for the stream. So if the `lnd` had actually hung up, it wouldn't detect that and would just keep spinning.
To make things more graceful, we also add back off when we try to reconnect.
=> funding: fix stream handling issues in consumePendingOpenChannels
