- account/manager.go
The auctioneer only expects one outstanding account reservation to exist per trader LSAT, so we should enforce this on the trader's side as well.
> account: ensure only one outstanding account reservation exists

- account/manager.go
This ensures that a trader cannot progress their account state without the server acknowledging their request. In the event where the server acknowledges the request and responds, and the trader shuts down before receiving the response, manual intervention will be required by the auctioneer to remove the pending modification. This serves as a stopgap to address the recent account modification issues until a better solution is in place (re-request signature for pending modification).
Motivated by https://github.com/lightninglabs/pool/issues/146 and https://github.com/lightninglabs/pool/issues/149.
> account: request signature before updating account due to modification

- order/interface.go
- order/interface_test.go
> order: account for last match consuming all units left in reserved value computation

- docs/faq.md
- docs/quickstart.md
Replaces #167.
Fixes #166.
Fixes #168.
> docs: update FAQ and quickstart doc

- version.go
Proposed release notes:
**Bug fixes**:
- Fix a problem in REST server that resulted in the `grpc: the client connection is closing` error: https://github.com/lightninglabs/pool/pull/175
- Fix `no order found` error when trying to close an account: https://github.com/lightninglabs/pool/pull/180
- Remove irritating error message `Unable to determine spend for account xxxx: context canceled`: https://github.com/lightninglabs/pool/pull/181
- Fix startup problem when pending batch was found in database: https://github.com/lightninglabs/pool/pull/179
- Fix typo in `pool` CLI: https://github.com/lightninglabs/pool/pull/182
- Add debug commands and wrap some errors to add more information: https://github.com/lightninglabs/pool/pull/178
**Improvements**:
- By default only show active accounts: …
> build: bump version to v0.3.4-alpha

- docs/orders.md
I kind of had a hard time finding how to cancel an order. When i finally found out, i thought it would be nice to add it here :)
> Added how to cancel orders.

- LICENSE
> pool: add MIT license

- clientdb/db.go
- macaroons.go
Fixes https://github.com/lightninglabs/pool/issues/177.
To make sure we don't just block for forever if another Pool daemon
process is already running, we add a timeout and error out if obtaining
the unique file lock fails after 5 seconds.
> macaroons+clientdb: add timeout to DB open

- auctioneer/client.go
- auto_sidecar.go
- clientdb/sidecar.go
- sidecar_acceptor.go
- sidecar_acceptor_test.go
Fixes some basic bugs, marking WIP until the set of unit tests is up.
> multi: sidecar bug fixes and additional tests

- auctioneer/client.go
We were missing a few selects on the quit channel which could lead to us
making another iteration in the loop while the server stream was already
set to nil. We fix that by making sure we always return one way or
another if the quit channel is closed.
Just to make the panic impossible to happen again, we also return from
the loop early if the server stream is nil, just in case.
> auctioneer: fix stream nil panic

- cmd/pool/account.go
- cmd/pool/auction.go
> Fix pool CLI short name conflict

- README.md
- docs/README.md
- docs/install.md
- go.mod
- go.sum
- version.go
> Fix auctioneerrpc tag, prepare for releasing v0.5.3-alpha

- README.md
> README: fix inprecise wording for execution fee

- rpcserver.go
Thaw height is now absoulte (used to be relative). We could check the
channel type (for type SCRIPT_ENFORCED_LEASE is always absolute) but
we can simply follow the ["500,000" value rule](https://github.com/lightningnetwork/lnd/blob/262591c3331c2170697fe89b8c49ab857db0adf7/channeldb/channel.go#L726).
> rpcserver: report lease expiries correctly

- rpcserver.go
> rpcserver: marshall channel type in order list

- cmd/pool/account.go
- cmd/pool/order.go
> Usability fixes

- version.go
> version: bump to v0.6.0-beta

- .editorconfig
- cmd/pool/order.go
Copied from lnd at commit 84401f6f6ce860728a8c009b2d28b1db9ddb36cd.
used.
> Add .editorconfig as copied from lnd.

- account/manager.go
Keep prefix tag, but drop the leading space: `poold -- `. Faraday looks for this tag.
Label  structure:
```json
{
"account":{
"action": "<action>",
"key": "<string>",
"expiry_height": <int>,
"output_index": <int>,
"expiry_spend": <bool>,
"tx_fee": <int>,
"balance_diff": <int>,
}
}
```
The `action` field takes one of the following values:
* `create`
* `deposit`
* `withdraw`
* `renew`
* `close`
`key` is the account key.
`expiry_height` is an integer block height at which the account expires. This value is important to ease the process of account recovery, see [here](https://github.com/lightninglabs/pool/pull/396#discussion_r1003366116).
`output_index` is an integer denoting the account balance transaction output.
`expiry_spend` is a boolean denoting whether the transaction spends via the …
> account: improve account onchain transaction labels

- cmd/pool/order.go
- funding/batch.go
Bonus: log returned errors by lnd when canceling a shim.
Fix #405
> cmd: update `--confirmation_constraints` description

- cmd/pool/order.go
Fixes the rest of https://github.com/lightninglabs/pool/issues/405.
used.
> cmd/pool: fix confirmation constraint description

- auctioneer/client.go
- cmd/pool/account.go
- tools/Dockerfile
Fixes https://github.com/lightninglabs/lightning-terminal/issues/470.
used.
> account recovery: increase default number of keys to try

- make/release_flags.mk
> build: add darwin-arm64 (Apple Silicon) as a release target

- cmd/poold/main.go
- run.go
Fixes https://github.com/lightninglabs/pool/issues/458.
used.
> Fix startup logging issues

- go.mod
> build: pin poolrpc
